# Dataset parameters
num_classes: 2
n_features: 50
n_redundant: 5
test_size: 0.4
training_samples_tot: 1000
random_state: 42

# Federated learning parameters
num_clients: 10
trees_client: 10
epochs: 5
rounds: 10


hyperparams:
  objective: binary:logistic
  n_estimators: 10
  max_depth: 5
  learning_rate: 0.1
  base_score: 0.5
  random_state: 34

